a=input("제품이름을 적어주세요")
b=int(input("제품의단가를 적어주세요"))
c=int(input("제품의 수량을 적어주세요"))
total=(int(b*c))
vat=(int(total*0.1))
alltotal=(total+vat)
print('='*38)
print(f"{'영수증':<10}")
print('='*38)
print(f"{a:<10}{c:^8}개{total:>6}원")
print('-'*38)
print(f"{'부가세(10%)':<10}{(vat):^8}원")
print(f"{'합계':<10}{alltotal:^8}원)")